In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4])

arr

print(arr)

[1 2 3 4]


In [5]:
print(np.__version__)

1.19.5


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
arr = np.array((1,2,3))

In [8]:
arr

array([1, 2, 3])

## 2 - D array

In [31]:
arr2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print (arr2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## 3-D array

In [10]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])

In [11]:
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## checking dimension

In [14]:
print(arr.ndim)

3


In [15]:
print(arr2d.ndim)

2


## indexing 
Accesing array element 

In [16]:
arr2d[0,1]

2

In [17]:
arr3d[1,0,1]

8

## slicing 

In [23]:
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [25]:
print(arr3d[0, 0:, 0:3:2])

[[1 3]
 [4 6]]


In [32]:
print(arr2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [33]:
print(arr2d[0:2, 2])

[3 8]


In [34]:
print(arr2d[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [35]:
print(arr3d.dtype)

int64


## Data Type

In [49]:
arr = np.array([-1,2,3,4], dtype = 'i4')

In [50]:
print(arr.dtype)

int32


In [51]:
new_arr = arr.astype('f')

In [52]:
print(new_arr)

[-1.  2.  3.  4.]


In [53]:
new = new_arr.astype(bool)

In [54]:
print(new)

[ True  True  True  True]


## Copy and View

In [66]:
x = arr.copy()

In [67]:
print(x)

[1 2 3 4]


In [68]:
x[0] = 0

In [69]:
print(x)

print(arr)

[0 2 3 4]
[1 2 3 4]


In [70]:
y = arr.view()

print(y)

[1 2 3 4]


In [72]:
arr[0] = 98

print(arr)

print(y)

[98  2  3  4]
[98  2  3  4]


In [76]:
print(x.base)

None


In [77]:
print(y.base)

[98  2  3  4]


In [81]:
print(arr2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [82]:
arr2d.shape

(2, 5)

In [83]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [84]:
arr3d.shape

(2, 2, 3)

In [85]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr)

new = arr.reshape(3,4)

print(new)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [86]:
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## Shape and Reshape

In [4]:
arr = np.array([1,2,4,5,6,7])

In [5]:
x = arr.reshape(1,2,3)

In [6]:
print(x)

[[[1 2 4]
  [5 6 7]]]


In [8]:
y = arr.reshape(3,2,1)

In [9]:
print(y)

[[[1]
  [2]]

 [[4]
  [5]]

 [[6]
  [7]]]


## Flattening Arrays
1. Converting Arrays into 1 Dimension

In [ ]:
y.shape