In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])

arr

print(arr)

[1 2 3 4]


In [3]:
print(np.__version__)

1.19.5


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
arr = np.array((1,2,3))

In [6]:
arr

array([1, 2, 3])

## 2 - D array

In [7]:
arr2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print (arr2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## 3-D array

In [8]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])

In [9]:
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [10]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## checking dimension

In [11]:
print(arr.ndim)

3


In [12]:
print(arr2d.ndim)

2


## indexing 
Accesing array element 

In [13]:
arr2d[0,1]

2

In [14]:
arr3d[1,0,1]

8

## slicing 

In [15]:
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [16]:
print(arr3d[0, 0:, 0:3:2])

[[1 3]
 [4 6]]


In [17]:
print(arr2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [18]:
print(arr2d[0:2, 2])

[3 8]


In [19]:
print(arr2d[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [20]:
print(arr3d.dtype)

int64


## Data Type

In [21]:
arr = np.array([-1,2,3,4], dtype = 'i4')

In [22]:
print(arr.dtype)

int32


In [23]:
new_arr = arr.astype('f')

In [24]:
print(new_arr)

[-1.  2.  3.  4.]


In [25]:
new = new_arr.astype(bool)

In [26]:
print(new)

[ True  True  True  True]


## Copy and View

In [27]:
x = arr.copy()

In [28]:
print(x)

[-1  2  3  4]


In [29]:
x[0] = 0

In [30]:
print(x)

print(arr)

[0 2 3 4]
[-1  2  3  4]


In [31]:
y = arr.view()

print(y)

[-1  2  3  4]


In [32]:
arr[0] = 98

print(arr)

print(y)

[98  2  3  4]
[98  2  3  4]


In [33]:
print(x.base)

None


In [34]:
print(y.base)

[98  2  3  4]


In [35]:
print(arr2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [36]:
arr2d.shape

(2, 5)

In [37]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [38]:
arr3d.shape

(2, 2, 3)

In [39]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr)

new = arr.reshape(3,4)

print(new)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## Shape and Reshape

In [41]:
arr = np.array([1,2,4,5,6,7])

In [42]:
x = arr.reshape(1,2,3)

In [43]:
print(x)

[[[1 2 4]
  [5 6 7]]]


In [44]:
y = arr.reshape(3,2,1)

In [45]:
print(y)

[[[1]
  [2]]

 [[4]
  [5]]

 [[6]
  [7]]]


## Flattening Arrays
1. Converting Arrays into 1 Dimension

In [46]:
y.shape

(3, 2, 1)

In [47]:
x = y.reshape(-1)

print(x)

[1 2 4 5 6 7]


## Iterating Through Arrays 

In [48]:
print(arr2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [49]:
for x in arr2d:
    print(x)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [50]:
for x in arr2d:
    for i in x:
        print(i)

1
2
3
4
5
6
7
8
9
10


In [51]:
for x in np.nditer(arr2d):
    print(x)

1
2
3
4
5
6
7
8
9
10


In [52]:
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [53]:
for x in arr3d:
    for i in x:
        for j in i:
            print(j)

1
2
3
4
5
6
7
8
9
10
11
12


## Joining Array

In [55]:
a = np.array([1,2,3,4])

b = np.array([5,6,7,8])

print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


### concatenation 
- np.conatenate()

In [78]:
d = np.dstack((a,b))
print(d)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [69]:
c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6 7 8]


In [60]:
x = np.array([[1,2,3,4], [5,6,7,8]])
xx = np.array([[5,6,7,8], [4,3,2,1]])

print(x)


[[1 2 3 4]
 [5 6 7 8]]


In [61]:
print(xx)

[[5 6 7 8]
 [4 3 2 1]]


In [72]:
xxx = np.concatenate((x,xx), axis = 0)

In [73]:
print(xxx)

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [4 3 2 1]]


### stacking

1. hstack - along the rows, axis = 1
2. vstack - along the columns, axis = 0
3. dstack - along depth 

In [75]:
xxs = np.hstack((x, xx))
print(xxs)

[[1 2 3 4 5 6 7 8]
 [5 6 7 8 4 3 2 1]]


In [77]:
xx2 = np.vstack((x,xx))
print(xx2)

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [4 3 2 1]]


In [79]:
xxd = np.dstack((x,xx))

In [80]:
print(xxd)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]

 [[5 4]
  [6 3]
  [7 2]
  [8 1]]]


## Splitting Array

In [82]:
s = np.array([1,2,3,4,5,6])
print(s)

[1 2 3 4 5 6]


In [89]:
x = np.array_split(s,4)
print(x)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [90]:
print(x[0])

[1 2]


In [91]:
xx

array([[5, 6, 7, 8],
       [4, 3, 2, 1]])

In [101]:
xs = np.array_split(xx, 2)
print(xs)

[array([[5, 6, 7, 8]]), array([[4, 3, 2, 1]])]


In [102]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

xc = np.array_split(arr, 6)
print(xc)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]]), array([[ 9, 10]]), array([[11, 12]])]


In [103]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [104]:
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [107]:
ax = np.array_split(arr, 3, axis = 1)

In [108]:
print(ax)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [110]:
hx = np.hsplit(arr, 3)
print(hx)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
